# Generated by Django 4.2.1 on 2024-10-03 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BushmanHuntingScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunting_limit', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Bushman Hunting Scopes',
                'db_table': 'bm_bushman_hunting_scopes',
            },
        ),
        migrations.CreateModel(
            name='Hunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=100)),
                ('passport_copy', models.FileField(upload_to='passport_copy/')),
                ('passport_photo', models.ImageField(upload_to='passport_photo/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hunter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hunters',
                'db_table': 'bm_hunters',
            },
        ),
        migrations.CreateModel(
            name='HuntingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Hunting Blocks',
                'db_table': 'bm_hunting_blocks',
            },
        ),
        migrations.CreateModel(
            name='HuntingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_in_number', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Hunting Days',
                'db_table': 'bm_hunting_days',
            },
        ),
        migrations.CreateModel(
            name='HuntingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1x1', '1x1'), ('2x1', '2x1'), ('3x1', '3x1'), ('4x1', '4x1'), ('5x1', '5x1'), ('6x1', '6x1'), ('7x1', '7x1'), ('8x1', '8x1'), ('9x1', '9x1'), ('10x1', '10x1')], max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Hunting Types',
                'db_table': 'bm_hunting_types',
            },
        ),
        migrations.CreateModel(
            name='SafariPackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Regular', 'Regular Safari'), ('Premium', 'Premium Safari'), ('Major', 'Major Safari')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Safari Package Types',
                'db_table': 'bm_safari_package_types',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Species',
                'db_table': 'bm_species',
            },
        ),
        migrations.CreateModel(
            name='SafariPackageHuntingSpeciesLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunting_limit', models.IntegerField(default=0)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits_species', to='hunter.safaripackagetype')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits_species', to='hunter.species')),
            ],
            options={
                'verbose_name_plural': 'Safari Package Hunting Species Limits',
                'db_table': 'bm_safari_package_hunting_species_limits',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hunting_limit', models.IntegerField(default=0)),
                ('hunting_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='hunter.huntingblock')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='hunter.species')),
            ],
            options={
                'verbose_name_plural': 'Quotas',
                'db_table': 'bm_quotas',
            },
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observer_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('passport_copy', models.FileField(upload_to='passport_copy/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Observers',
                'db_table': 'bm_observers',
            },
        ),
        migrations.CreateModel(
            name='HunterHuntingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfitter', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hunt_days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunt_days', to='hunter.huntingdays')),
                ('hunt_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_type', to='hunter.huntingtype')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_details', to='hunter.hunter')),
                ('hunting_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_block', to='hunter.huntingblock')),
                ('species_to_be_hunted', models.ManyToManyField(to='hunter.bushmanhuntingscope')),
            ],
            options={
                'verbose_name_plural': 'Hunt Details',
                'db_table': 'bm_hunt_details',
            },
        ),
        migrations.AddField(
            model_name='bushmanhuntingscope',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bushman_hunting_scope', to='hunter.huntingblock'),
        ),
        migrations.AddField(
            model_name='bushmanhuntingscope',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bushman_hunting_scope', to='hunter.species'),
        ),
    ]
