# Generated by Django 4.2.1 on 2024-10-03 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observer',
            name='passport_copy',
        ),
        migrations.CreateModel(
            name='TrophyShippingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=100)),
                ('taxidermist', models.CharField(max_length=100)),
                ('port_of_entry', models.CharField(max_length=100)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophy_shipping_detail', to='hunter.hunter')),
            ],
            options={
                'verbose_name_plural': 'Trophy Shipping Details',
                'db_table': 'bm_trophy_shipping_details',
            },
        ),
        migrations.CreateModel(
            name='HunterWeapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('caliber', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('ammo_quantity', models.IntegerField(default=0)),
                ('maker_number', models.CharField(max_length=100)),
                ('weapon_owner', models.CharField(max_length=100)),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunter_weapons', to='hunter.hunter')),
            ],
            options={
                'verbose_name_plural': 'Hunter Weapons',
                'db_table': 'bm_hunter_weapons',
            },
        ),
        migrations.CreateModel(
            name='HunterItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_arrival', models.CharField(max_length=100)),
                ('airport_departure', models.CharField(max_length=100)),
                ('charter_flight_arrangements', models.TextField()),
                ('hotel_bookings', models.TextField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunter_itinerary', to='hunter.hunter')),
            ],
            options={
                'verbose_name_plural': 'Hunter Itineraries',
                'db_table': 'bm_hunter_itineraries',
            },
        ),
        migrations.CreateModel(
            name='HunterDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('Travel Packet', 'Travel Packet(Passport Copy)'), ('Visa', 'Visa'), ('Gun Permits', 'Gun Permits'), ('CITES Documentation', 'CITES Documentation')], max_length=100)),
                ('document', models.FileField(upload_to='documents/')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunder_documents', to='hunter.hunter')),
            ],
            options={
                'verbose_name_plural': 'Hunter Documents',
                'db_table': 'bm_hunter_documents',
            },
        ),
        migrations.CreateModel(
            name='ClientPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_preferences', models.TextField()),
                ('beverage_preferences', models.TextField()),
                ('allergies', models.TextField()),
                ('alcohol_preferences', models.TextField()),
                ('clothing_gear_needs', models.TextField()),
                ('special_requests', models.TextField()),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_preferences', to='hunter.hunter')),
            ],
            options={
                'verbose_name_plural': 'Client Preferences',
                'db_table': 'bm_client_preferences',
            },
        ),
    ]
