# Generated by Django 4.2.1 on 2024-10-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0002_remove_observer_passport_copy_trophyshippingdetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterhuntingdetails',
            name='outfitter',
            field=models.CharField(default='Bushman Safari Trackers Limited', max_length=100),
        ),
    ]
