# Generated by Django 4.2.1 on 2024-10-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0003_alter_hunterhuntingdetails_outfitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunter',
            name='passport_copy',
        ),
        migrations.RemoveField(
            model_name='hunter',
            name='passport_photo',
        ),
        migrations.AlterField(
            model_name='hunterdocument',
            name='document_type',
            field=models.CharField(choices=[('Passport_Copy', 'Travel Packet(Passport Copy)'), ('Passport_Photo', 'Travel Packet(Passport  Photo'), ('Observer_Passport_Copy', "Observer's Passport copy"), ('Visa', 'Visa'), ('Gun Permits', 'Gun Permits'), ('CITES Documentation', 'CITES Documentation')], max_length=100),
        ),
        migrations.AlterField(
            model_name='hunteritinerary',
            name='hotel_bookings',
            field=models.TextField(help_text='Number of rooms and types required'),
        ),
    ]
