# Generated by Django 4.2.1 on 2024-10-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0005_hunter_hunter_role_professionhunter_companionhunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='companionhunter',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companionhunter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companionhunter',
            name='email_address',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companionhunter',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='companions/'),
        ),
        migrations.AddField(
            model_name='companionhunter',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companionhunter',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
