# Generated by Django 4.2.1 on 2024-10-03 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0006_companionhunter_address_companionhunter_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('licence_document', models.FileField(upload_to='documents/')),
                ('hunter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_license', to='hunter.hunter')),
            ],
            options={
                'verbose_name_plural': 'Hunting Licenses',
                'db_table': 'bm_hunting_licenses',
            },
        ),
        migrations.AddField(
            model_name='hunterhuntingdetails',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_package_type', to='hunter.safaripackagetype'),
        ),
        migrations.AlterField(
            model_name='hunterhuntingdetails',
            name='hunt_days',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HuntingDays',
        ),
    ]
