# Generated by Django 4.2.1 on 2024-10-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0007_huntinglicense_hunterhuntingdetails_package_type_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companionhunter',
            table='bm_companion_hunters',
        ),
    ]
