# Generated by Django 4.2.1 on 2024-10-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0008_alter_companionhunter_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaripackagetype',
            name='safari_duration',
            field=models.IntegerField(default=0),
        ),
    ]
