# Generated by Django 5.0.4 on 2024-10-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0001_initial'),
        ('hunter', '0009_safaripackagetype_safari_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunterhuntingdetails',
            name='hunting_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_block', to='bm_hunting_settings.huntingblock'),
        ),
        migrations.RemoveField(
            model_name='quota',
            name='hunting_block',
        ),
        migrations.AlterField(
            model_name='hunterhuntingdetails',
            name='hunt_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_type', to='bm_hunting_settings.huntingtype'),
        ),
        migrations.RemoveField(
            model_name='quota',
            name='species',
        ),
        migrations.RemoveField(
            model_name='safaripackagehuntingspecieslimit',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='safaripackagehuntingspecieslimit',
            name='species',
        ),
        migrations.AlterField(
            model_name='hunterhuntingdetails',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_package_type', to='bm_hunting_settings.safaripackagetype'),
        ),
        migrations.AlterField(
            model_name='hunterhuntingdetails',
            name='species_to_be_hunted',
            field=models.ManyToManyField(to='bm_hunting_settings.bushmanhuntingscope'),
        ),
        migrations.DeleteModel(
            name='BushmanHuntingScope',
        ),
        migrations.DeleteModel(
            name='HuntingBlock',
        ),
        migrations.DeleteModel(
            name='HuntingType',
        ),
        migrations.DeleteModel(
            name='Quota',
        ),
        migrations.DeleteModel(
            name='SafariPackageHuntingSpeciesLimit',
        ),
        migrations.DeleteModel(
            name='Species',
        ),
        migrations.DeleteModel(
            name='SafariPackageType',
        ),
    ]
