# Generated by Django 5.0.4 on 2024-10-03 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0010_alter_hunterhuntingdetails_hunting_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophyshippingdetail',
            name='hunter',
        ),
        migrations.DeleteModel(
            name='HunterHuntingDetails',
        ),
        migrations.DeleteModel(
            name='TrophyShippingDetail',
        ),
    ]
