# Generated by Django 5.0.4 on 2024-10-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0012_rename_hunter_client_remove_professionhunter_hunter'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='clients',
        ),
        migrations.AlterModelTable(
            name='clientpreferences',
            table='client_preferences',
        ),
        migrations.AlterModelTable(
            name='companionhunter',
            table='companion_hunters',
        ),
        migrations.AlterModelTable(
            name='hunterdocument',
            table='hunter_documents',
        ),
        migrations.AlterModelTable(
            name='hunteritinerary',
            table='hunter_itineraries',
        ),
        migrations.AlterModelTable(
            name='hunterweapon',
            table='hunter_weapons',
        ),
        migrations.AlterModelTable(
            name='huntinglicense',
            table='hunting_licenses',
        ),
        migrations.AlterModelTable(
            name='observer',
            table='observers',
        ),
        migrations.AlterModelTable(
            name='professionhunter',
            table='profession_hunters',
        ),
    ]
