# Generated by Django 5.0.4 on 2024-10-03 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0013_alter_client_table_alter_clientpreferences_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clients'},
        ),
    ]
