# Generated by Django 5.0.4 on 2024-10-03 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0016_weapon_remove_hunterweapon_hunter_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientdocument',
            options={'verbose_name_plural': 'Client Documents'},
        ),
        migrations.AlterModelOptions(
            name='hunteritinerary',
            options={'verbose_name_plural': 'client Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name_plural': 'Weapons'},
        ),
        migrations.AlterModelTable(
            name='clientdocument',
            table='client_documents',
        ),
        migrations.AlterModelTable(
            name='clientpreferences',
            table='client_preferences',
        ),
        migrations.AlterModelTable(
            name='huntingclientlicense',
            table='client_hunting_licenses',
        ),
        migrations.AlterModelTable(
            name='weapon',
            table='weapons',
        ),
    ]
