# Generated by Django 5.0.4 on 2024-10-03 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0008_remove_package_end_date_remove_package_start_date'),
        ('hunter', '0017_alter_clientdocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinetSalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('order_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to='hunter.client')),
                ('package', models.ManyToManyField(related_name='sales_order_package', to='bm_hunting_settings.package')),
            ],
            options={
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'client_sales_orders',
            },
        ),
    ]
