# Generated by Django 5.0.4 on 2024-10-04 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0019_clientcustomizablepackage_clientsalesorder_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientsalesorder',
            table='client_sales_orders',
        ),
    ]
