# Generated by Django 5.0.4 on 2024-10-04 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0022_clientsalesorder_observer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsalesorder',
            name='companion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companion_sales_orders', to='hunter.client'),
        ),
    ]
