# Generated by Django 5.0.4 on 2024-10-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0023_clientsalesorder_companion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsalesorder',
            name='order_date',
            field=models.DateField(null=True),
        ),
    ]
