# Generated by Django 5.0.4 on 2024-10-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0014_remove_package_trophy_fees_list'),
        ('hunter', '0024_clientsalesorder_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsalesorder',
            name='pre_def_package',
            field=models.ManyToManyField(to='bm_hunting_settings.package'),
        ),
    ]
