# Generated by Django 5.0.4 on 2024-10-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0026_clientsalesorder_package_customized'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientCustomizablePackage',
        ),
    ]
