# Generated by Django 5.0.4 on 2024-10-04 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0028_clientcustomizablepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsalesorder',
            name='customizable_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hunter.clientcustomizablepackage'),
        ),
    ]
