# Generated by Django 5.0.4 on 2024-10-04 07:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0014_remove_package_trophy_fees_list'),
        ('hunter', '0029_clientsalesorder_customizable_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcustomizablepackage',
            name='name',
        ),
        migrations.AddField(
            model_name='clientcustomizablepackage',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='clientcustomizablepackage',
            name='hunting_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizable_packages', to='bm_hunting_settings.huntingblock'),
        ),
        migrations.AddField(
            model_name='clientcustomizablepackage',
            name='hunting_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizable_packages', to='bm_hunting_settings.huntingtype'),
        ),
        migrations.AddField(
            model_name='clientcustomizablepackage',
            name='number_of_days',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientcustomizablepackage',
            name='number_of_hunters',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='clientcustomizablepackage',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizable_packages', to='bm_hunting_settings.safaripackagetype'),
        ),
        migrations.AddField(
            model_name='clientcustomizablepackage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
