# Generated by Django 5.0.4 on 2024-10-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0030_remove_clientcustomizablepackage_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsalesorder',
            name='confirm_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientsalesorder',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clientsalesorder',
            name='payment_document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='clientsalesorder',
            name='payment_status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientsalesorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='clientsalesorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
