# Generated by Django 5.0.4 on 2024-10-04 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0031_clientsalesorder_confirm_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsalesorder',
            name='companion',
        ),
        migrations.RemoveField(
            model_name='clientsalesorder',
            name='observer',
        ),
    ]
