# Generated by Django 5.0.4 on 2024-10-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0036_client_passport_number'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companion',
            table='companions',
        ),
    ]
