# Generated by Django 5.0.4 on 2024-10-05 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0038_alter_client_user_alter_companion_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passport_number',
        ),
    ]
