# Generated by Django 4.2.9 on 2024-10-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0041_alter_clientdocument_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdocument',
            name='forWho',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientdocument',
            unique_together={('forWho', 'document_type')},
        ),
    ]
