# Generated by Django 4.2.9 on 2024-10-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0042_clientdocument_forwho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdocument',
            name='forWho',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
