# Generated by Django 4.2.9 on 2024-10-06 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0043_alter_clientdocument_forwho'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_arrival', models.CharField(max_length=100)),
                ('airport_departure', models.CharField(max_length=100)),
                ('charter_flight_arrangements', models.TextField()),
                ('hotel_bookings', models.TextField(help_text='Number of rooms and types required')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_itinerary', to='hunter.client')),
            ],
            options={
                'verbose_name_plural': 'client Itineraries',
            },
        ),
        migrations.DeleteModel(
            name='HunterItinerary',
        ),
    ]
