# Generated by Django 4.2.9 on 2024-10-07 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0044_clientitinerary_delete_hunteritinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=200)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('nationality', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='EntityCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Entity Categories',
                'db_table': 'entity_categories',
            },
        ),
        migrations.CreateModel(
            name='EntityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_category', to='hunter.entitycategories')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_category', to='hunter.entity')),
            ],
            options={
                'verbose_name_plural': 'Entity Categories',
                'db_table': 'entity_category',
            },
        ),
    ]
