# Generated by Django 4.2.9 on 2024-10-07 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0014_remove_package_trophy_fees_list'),
        ('hunter', '0045_entity_entitycategories_entitycategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityHuntingInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_hunters', models.IntegerField(default=0)),
                ('number_of_days', models.IntegerField(default=0)),
                ('number_companions', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_set', to='hunter.entity')),
                ('hunting_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_hunting_area_set', to='bm_hunting_settings.huntingblock')),
                ('hunting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_hunting_type_set', to='bm_hunting_settings.huntingtype')),
                ('safari_package_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_safari_package_type_set', to='bm_hunting_settings.safaripackagetype')),
                ('species_to_hunt', models.ManyToManyField(to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Entity Hunting Infos',
                'db_table': 'entity_hunting_infos',
            },
        ),
    ]
