# Generated by Django 4.2.9 on 2024-10-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0046_entityhuntinginfos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entitycategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='entitycategory',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='hunting_area',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='hunting_type',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='safari_package_type',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='species_to_hunt',
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='EntityCategories',
        ),
        migrations.DeleteModel(
            name='EntityCategory',
        ),
        migrations.DeleteModel(
            name='EntityHuntingInfos',
        ),
    ]
