# Generated by Django 4.2.9 on 2024-10-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0048_rename_clientdocument_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
