# Generated by Django 4.2.9 on 2024-10-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0051_weapontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsalesorder',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientsalesorder',
            name='customizable_package',
        ),
        migrations.RemoveField(
            model_name='clientsalesorder',
            name='pre_def_package',
        ),
        migrations.RemoveField(
            model_name='huntingclientlicense',
            name='client',
        ),
        migrations.DeleteModel(
            name='ClientCustomizablePackage',
        ),
        migrations.DeleteModel(
            name='ClientSalesOrder',
        ),
        migrations.DeleteModel(
            name='HuntingClientLicense',
        ),
    ]
