# Generated by Django 4.2.9 on 2024-10-21 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunter', '0052_remove_clientsalesorder_client_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientItinerary',
        ),
    ]
