# Generated by Django 5.1.2 on 2024-12-16 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('approval_chain', '0001_initial'),
        ('bm_hunting_settings', '0018_alter_salespackagespecies_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Requisition Items',
                'db_table': 'requisition_items',
            },
        ),
        migrations.CreateModel(
            name='RequestItemItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measurement', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriptions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bm_hunting_settings.currency')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.requestitem')),
            ],
            options={
                'verbose_name_plural': 'Requisition Item Items',
                'db_table': 'requisition_item_items',
            },
        ),
        migrations.CreateModel(
            name='RequestItemAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descriptions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bm_hunting_settings.currency')),
                ('requisition_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.requestitemitems')),
            ],
            options={
                'verbose_name_plural': 'Requisition Item Accounts',
                'db_table': 'requisition_item_accounts',
            },
        ),
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GAME_REQ', 'Game Requisition'), ('GENERAL', 'General Requisition')], max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('required_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=255)),
                ('remarks', models.TextField()),
                ('is_printed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_chain_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_chain.approvalchainmodule')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_chain.approvalchainlevels')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requisitions',
                'db_table': 'requisitions',
            },
        ),
        migrations.CreateModel(
            name='RequestItemSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CASH', 'Cash'), ('STORE', 'Store'), ('VENDOR', 'Vendor')], max_length=255)),
                ('payee', models.CharField(max_length=255)),
                ('account', models.CharField(max_length=255)),
                ('mode_of_payment', models.CharField(choices=[('CASH', 'Cash'), ('TT', 'TT'), ('CREDIT', 'Credit')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bm_hunting_settings.currency')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.requisition')),
            ],
            options={
                'verbose_name_plural': 'Requisition Item Sources',
                'db_table': 'requisition_item_sources',
            },
        ),
        migrations.AddField(
            model_name='requestitem',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.requisition'),
        ),
    ]
