# Generated by Django 5.1.2 on 2024-12-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0004_alter_approvalchainlevels_position'),
        ('requisition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='approval_chain_module',
        ),
        migrations.AddField(
            model_name='requisition',
            name='approval_chain_module',
            field=models.ManyToManyField(to='approval_chain.approvalchainmodule'),
        ),
    ]
