# Generated by Django 5.1.2 on 2024-12-17 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0013_alter_approvalchainlevels_approval_chain_module'),
        ('requisition', '0002_remove_requisition_approval_chain_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='approval_chain_module',
        ),
        migrations.AddField(
            model_name='requisition',
            name='approval_chain_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='approval_chain.approvalchainmodule'),
        ),
    ]
