# Generated by Django 5.1.2 on 2024-12-17 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0003_remove_requisition_approval_chain_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitemaccount',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requestitemaccount',
            name='requisition_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requisition.requestitem'),
        ),
        migrations.AlterField(
            model_name='requestitemitems',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
