# Generated by Django 5.1.2 on 2024-12-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0005_alter_requestitemsource_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitemaccount',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
