# Generated by Django 5.1.2 on 2024-12-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0007_requestitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestitemitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_items_set', to='requisition.requestitem'),
        ),
    ]
