# Generated by Django 5.1.2 on 2024-12-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0010_alter_requisition_approval_chain_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestitemitems',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
