# Generated by Django 5.1.2 on 2024-12-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0014_requisitionapprovalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled'), ('IN_PRGRESS', 'In Progress')], max_length=255),
        ),
    ]
