# Generated by Django 5.1.2 on 2024-12-27 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0015_alter_approvalchainlevels_status'),
        ('requisition', '0016_alter_requisition_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionapprovalstatus',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_status_set', to='approval_chain.approvalchainlevels'),
        ),
        migrations.AlterField(
            model_name='requisitionapprovalstatus',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_status_set', to='requisition.requisition'),
        ),
        migrations.AlterField(
            model_name='requisitionapprovalstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
