# Generated by Django 5.1.4 on 2025-01-02 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requisition', '0017_alter_requisitionapprovalstatus_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionapprovalstatus',
            name='requisition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_level_status_set', to='requisition.requisition'),
        ),
    ]
