# Generated by Django 5.1.2 on 2024-12-16 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalChainModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Approval Chain Modules',
                'db_table': 'approval_chain_modules',
            },
        ),
        migrations.CreateModel(
            name='ApprovalChainRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('past', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Approval Chain Roles',
                'db_table': 'approval_chain_roles',
            },
        ),
        migrations.CreateModel(
            name='ApprovalChainLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_change_source', models.BooleanField(default=False)),
                ('position', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_chain_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_chain.approvalchainmodule')),
                ('approval_chain_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_chain.approvalchainrole')),
            ],
            options={
                'verbose_name_plural': 'Approval Chain Levels',
                'db_table': 'approval_chain_levels',
            },
        ),
        migrations.CreateModel(
            name='ApprovalChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('approval_chain_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_chain.approvalchainlevels')),
                ('approval_chain_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='approval_chain.approvalchainmodule')),
            ],
            options={
                'verbose_name_plural': 'Approval Chains',
                'db_table': 'approval_chains',
            },
        ),
    ]
