# Generated by Django 5.1.2 on 2024-12-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0003_alter_approvalchainrole_past'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchainlevels',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
