# Generated by Django 5.1.2 on 2024-12-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0005_alter_approvalchainrole_past'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchainmodule',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
