# Generated by Django 5.1.2 on 2024-12-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0006_alter_approvalchainmodule_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchainmodule',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='approvalchainrole',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='approvalchainlevels',
            unique_together={('approval_chain_module', 'approval_chain_role')},
        ),
    ]
