# Generated by Django 5.1.2 on 2024-12-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0008_approvalchainlevels_leve_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalchainlevels',
            old_name='leve_number',
            new_name='level_number',
        ),
    ]
