# Generated by Django 5.1.2 on 2024-12-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0009_rename_leve_number_approvalchainlevels_level_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalchainmodule',
            old_name='descriptions',
            new_name='description',
        ),
    ]
