# Generated by Django 5.1.2 on 2024-12-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0010_rename_descriptions_approvalchainmodule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchainlevels',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=255, null=True),
        ),
    ]
