# Generated by Django 5.1.2 on 2024-12-17 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0011_alter_approvalchainlevels_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchain',
            name='approval_chain_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chains', to='approval_chain.approvalchainmodule'),
        ),
    ]
