# Generated by Django 5.1.2 on 2024-12-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0013_alter_approvalchainlevels_approval_chain_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchainlevels',
            name='level_number',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
