# Generated by Django 5.1.2 on 2024-12-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_chain', '0014_alter_approvalchainlevels_level_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalchainlevels',
            name='status',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('VISITED', 'Completed'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=255, null=True),
        ),
    ]
