# Generated by Django 5.0.4 on 2024-10-04 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userprofile_bio_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='passport_number',
        ),
    ]
