# Generated by Django 5.0.4 on 2024-10-05 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_userprofile_passport_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
