# Generated by Django 4.2.9 on 2024-10-21 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0057_rename_prefferred_date_salesiquirypreference_preferred_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesConfirmationProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_date', models.DateField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_proposal_client', to='sales.entity')),
                ('sales_inquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_proposal', to='sales.salesinquiry')),
            ],
        ),
    ]
