# Generated by Django 4.2.9 on 2024-10-21 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesconfirmationproposal',
            options={'verbose_name_plural': 'Sales Confirmation Proposals'},
        ),
        migrations.AlterModelTable(
            name='salesconfirmationproposal',
            table='sales_confirmation_proposal',
        ),
    ]
