# Generated by Django 4.2.9 on 2024-10-21 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0088_alter_species_description'),
        ('sales_confirmation', '0002_alter_salesconfirmationproposal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfirmationproposal',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SalesConfirmationProposalPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunting_license', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_package_package', to='bm_hunting_settings.salespackage')),
                ('sales_confirmation_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_package', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Packages',
                'db_table': 'sales_confirmation_package',
            },
        ),
        migrations.CreateModel(
            name='SalesConfirmationProposalItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('departure', models.DateField(blank=True, null=True)),
                ('arrival_timezone', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('charters', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('departure_timezone', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('hotel_booking', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_confirmation_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Itineraries',
                'db_table': 'sales_confirmation_itinerary',
                'ordering': ['departure'],
            },
        ),
        migrations.CreateModel(
            name='SalesConfirmationProposalClientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_name', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_confirmation_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_preferences', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Client Preferences',
                'db_table': 'sales_confirmation_client_preference',
            },
        ),
        migrations.CreateModel(
            name='SalesConfirmationProposalAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_confirmation_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Additional Services',
                'db_table': 'sales_confirmation_additional_service',
            },
        ),
    ]
