# Generated by Django 4.2.9 on 2024-10-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0004_rename_arrival_timezone_salesconfirmationproposalitinerary_arrival_tz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesconfirmationproposalitinerary',
            old_name='arrival_tz',
            new_name='arrival',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalitinerary',
            name='departure_tz',
        ),
    ]
