# Generated by Django 4.2.9 on 2024-10-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0004_installment_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installment',
            name='due_limit',
            field=models.CharField(choices=[('prior', 'Due Before the Due Date'), ('after', 'Due After the Due Date'), ('none', 'No Due Date')], default='none', max_length=255),
        ),
    ]
