# Generated by Django 4.2.9 on 2024-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0005_rename_arrival_tz_salesconfirmationproposalitinerary_arrival_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposalitinerary',
            name='arrival',
            field=models.DateField(blank=True, null=True),
        ),
    ]
