# Generated by Django 4.2.9 on 2024-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0006_alter_salesconfirmationproposalitinerary_arrival'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesconfirmationproposalitinerary',
            old_name='airport',
            new_name='airport_name',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalitinerary',
            name='charters',
        ),
        migrations.AddField(
            model_name='salesconfirmationproposalitinerary',
            name='charter_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesconfirmationproposalitinerary',
            name='charter_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
