# Generated by Django 4.2.9 on 2024-10-25 10:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0006_remove_installment_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesConfirmationProposalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('provission_sales', 'Provission Sales'), ('Confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_confirmation_proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Status',
                'db_table': 'sales_confirmation_status',
            },
        ),
    ]
