# Generated by Django 4.2.9 on 2024-10-25 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0007_salesconfirmationproposalstatus'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesconfirmationproposalstatus',
            table='sales_confirmation',
        ),
    ]
