# Generated by Django 4.2.9 on 2024-10-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0007_rename_airport_salesconfirmationproposalitinerary_airport_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesconfirmationproposalitinerary',
            options={'verbose_name_plural': 'Sales Confirmation Itineraries'},
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalitinerary',
            name='departure',
        ),
        migrations.AlterField(
            model_name='salesconfirmationproposalitinerary',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
