# Generated by Django 4.2.9 on 2024-10-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0008_alter_salesconfirmationproposalitinerary_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposalitinerary',
            name='sales_confirmation_proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='sales_confirmation.salesconfirmationproposal'),
        ),
    ]
