# Generated by Django 4.2.9 on 2024-10-25 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_doctype_code'),
        ('sales_confirmation', '0008_alter_salesconfirmationproposalstatus_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfirmationproposalstatus',
            name='documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_status_documents', to='sales.document'),
        ),
    ]
