# Generated by Django 4.2.9 on 2024-10-25 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0009_salesconfirmationproposalstatus_documents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesconfirmationproposalstatus',
            old_name='documents',
            new_name='document',
        ),
    ]
