# Generated by Django 4.2.9 on 2024-10-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_rename_prefferred_date_salesiquirypreference_preferred_date'),
        ('sales_confirmation', '0009_alter_salesconfirmationproposalitinerary_sales_confirmation_proposal'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesconfirmationproposal',
            unique_together={('sales_inquiry', 'id')},
        ),
    ]
