# Generated by Django 4.2.9 on 2024-10-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0057_rename_prefferred_date_salesiquirypreference_preferred_date'),
        ('sales_confirmation', '0010_alter_salesconfirmationproposal_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposal',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_proposal_client', to='sales.entity'),
        ),
        migrations.AlterField(
            model_name='salesconfirmationproposal',
            name='sales_inquiry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_proposal', to='sales.salesinquiry'),
        ),
        migrations.AlterField(
            model_name='salesconfirmationproposaladditionalservice',
            name='sales_confirmation_proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='sales_confirmation.salesconfirmationproposal'),
        ),
        migrations.AlterField(
            model_name='salesconfirmationproposalpackage',
            name='sales_confirmation_proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_package', to='sales_confirmation.salesconfirmationproposal'),
        ),
    ]
