# Generated by Django 4.2.9 on 2024-10-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_document_options'),
        ('sales_confirmation', '0010_rename_documents_salesconfirmationproposalstatus_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposalstatus',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_confirmation_status_documents', to='sales.document'),
        ),
    ]
