# Generated by Django 4.2.9 on 2024-10-22 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0011_alter_salesconfirmationproposal_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposaladditionalservice',
            name='sales_confirmation_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='sales_confirmation.salesconfirmationproposal'),
        ),
    ]
