# Generated by Django 4.2.9 on 2024-10-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0012_alter_salesconfirmationproposaladditionalservice_sales_confirmation_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposal',
            name='confirmation_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
