# Generated by Django 4.2.9 on 2024-10-22 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0013_alter_salesconfirmationproposal_confirmation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('sales_confirmation_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Installments',
                'db_table': 'sales_confirmation_installment',
            },
        ),
    ]
