# Generated by Django 4.2.9 on 2024-10-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0014_alter_salesconfirmationproposalstatus_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesconfirmationproposal',
            table='sales_confirmation_proposals',
        ),
    ]
