# Generated by Django 4.2.9 on 2024-10-26 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0015_alter_salesconfirmationproposal_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesconfirmationproposal',
            table=None,
        ),
    ]
