# Generated by Django 4.2.9 on 2024-10-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0014_alter_regulatoryhuntingpackage_name'),
        ('sales_confirmation', '0017_salesquotaspeciesstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfirmationproposal',
            name='regulatory_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_proposal_regulatory_package', to='bm_hunting_settings.regulatoryhuntingpackage'),
        ),
    ]
