# Generated by Django 5.1.2 on 2024-11-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0017_alter_huntingpackagecompanionshunter_days_and_more'),
        ('sales_confirmation', '0018_salesconfirmationproposal_regulatory_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotaspeciesstatus',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_sales_quota_status_set', to='bm_hunting_settings.quota'),
        ),
    ]
