# Generated by Django 5.1.2 on 2024-11-11 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0020_salesconfirmationcontract'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesconfirmationcontract',
            table='enity_contract',
        ),
    ]
