# Generated by Django 5.1.2 on 2024-11-11 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0024_enitycontractpermit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enitycontactdates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enitycontactdates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gameactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
