# Generated by Django 5.1.2 on 2024-11-11 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_salesiquirypreference_no_of_companions_and_more'),
        ('sales_confirmation', '0025_enitycontactdates_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameactivity',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_activity_client_set', to='sales.entity'),
        ),
        migrations.CreateModel(
            name='GameActivityProfessionalHunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_hunter_set', to='sales_confirmation.gameactivity')),
                ('hunter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_activity_professional_hunter_set', to='sales.entity')),
            ],
            options={
                'verbose_name_plural': 'Game Activity Professional Hunters',
                'db_table': 'game_activity_professional_hunter',
            },
        ),
    ]
