# Generated by Django 5.1.2 on 2024-11-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0026_gameactivity_client_gameactivityprofessionalhunter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesconfirmationcontract',
            old_name='enity',
            new_name='entity',
        ),
    ]
