# Generated by Django 5.1.2 on 2024-11-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0027_rename_enity_salesconfirmationcontract_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesconfirmationcontract',
            name='contract_amount',
        ),
    ]
