# Generated by Django 5.1.2 on 2024-11-11 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_salesiquirypreference_no_of_companions_and_more'),
        ('sales_confirmation', '0028_remove_salesconfirmationcontract_contract_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesconfirmationcontract',
            unique_together={('sales_confirmation_proposal', 'entity')},
        ),
    ]
