# Generated by Django 5.1.2 on 2024-11-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0029_alter_salesconfirmationcontract_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnityContactDates',
            new_name='EntityContactDates',
        ),
    ]
