# Generated by Django 5.1.2 on 2024-11-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0017_alter_huntingpackagecompanionshunter_days_and_more'),
        ('sales_confirmation', '0030_rename_enitycontactdates_entitycontactdates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnityContractPermit',
            new_name='EntityContractPermit',
        ),
        migrations.AlterModelTable(
            name='entitycontractpermit',
            table='entity_contract_permit',
        ),
    ]
