# Generated by Django 5.1.2 on 2024-11-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0031_rename_enitycontractpermit_entitycontractpermit_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityContactDates',
            new_name='EntityContactPermitDates',
        ),
    ]
