# Generated by Django 5.1.2 on 2024-11-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0032_rename_entitycontactdates_entitycontactpermitdates'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entitycontactpermitdates',
            table='enity_contact_permit_dates',
        ),
    ]
