# Generated by Django 5.1.2 on 2024-11-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0033_alter_entitycontactpermitdates_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameactivityprofessionalhunter',
            old_name='hunter',
            new_name='ph',
        ),
    ]
