# Generated by Django 5.1.2 on 2024-11-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_salesiquirypreference_no_of_companions_and_more'),
        ('sales_confirmation', '0034_rename_hunter_gameactivityprofessionalhunter_ph'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameactivity',
            unique_together={('entity_contract_permit', 'client')},
        ),
    ]
