# Generated by Django 5.1.2 on 2024-11-12 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0035_alter_gameactivity_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitycontractpermit',
            name='enity_contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='sales_confirmation.salesconfirmationcontract'),
        ),
    ]
