# Generated by Django 5.1.2 on 2024-11-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0017_alter_huntingpackagecompanionshunter_days_and_more'),
        ('sales_confirmation', '0036_alter_entitycontractpermit_enity_contract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitycontractpermit',
            options={'verbose_name_plural': 'Entity Contract Permits'},
        ),
        migrations.RenameField(
            model_name='entitycontractpermit',
            old_name='enity_contract',
            new_name='entity_contract',
        ),
        migrations.AlterField(
            model_name='entitycontractpermit',
            name='package_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_contract_permit_package_type_set', to='bm_hunting_settings.regulatoryhuntingpackage'),
        ),
    ]
