# Generated by Django 5.1.2 on 2024-11-13 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0017_alter_huntingpackagecompanionshunter_days_and_more'),
        ('sales_confirmation', '0037_alter_entitycontractpermit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamekilledactivity',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_killed_activity_area_set', to='bm_hunting_settings.huntingarea'),
        ),
        migrations.AddField(
            model_name='gamekilledactivity',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamekilledactivity',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamekilledactivity',
            name='weapon_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
