# Generated by Django 5.1.2 on 2024-11-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0038_gamekilledactivity_area_gamekilledactivity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamekilledactivity',
            name='status',
            field=models.CharField(blank=True, choices=[('KILLED', 'Killed'), ('WOUNDED', 'Wounded')], max_length=255, null=True),
        ),
    ]
