# Generated by Django 5.1.2 on 2024-11-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0039_alter_gamekilledactivity_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installment',
            old_name='days',
            new_name='due_days',
        ),
        migrations.RenameField(
            model_name='installment',
            old_name='description',
            new_name='narration',
        ),
        migrations.AddField(
            model_name='installment',
            name='amount_due_type',
            field=models.CharField(blank=True, choices=[('PERCENT', 'PERCENT'), ('LAPS', 'LAPS')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='due_days_type',
            field=models.CharField(blank=True, choices=[('UPON_SALES_CONFIRMATION', 'Upon Sales Confirmation'), ('PRIOR_SAFARI', 'Prior to Safari')], max_length=255, null=True),
        ),
    ]
