# Generated by Django 5.1.2 on 2024-11-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0040_rename_days_installment_due_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installment',
            name='due_limit',
        ),
    ]
