# Generated by Django 5.1.2 on 2024-11-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0041_remove_installment_due_limit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='installment',
            table='installment_setups',
        ),
    ]
