# Generated by Django 5.1.2 on 2024-11-25 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0042_alter_installment_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposalpackage',
            name='sales_confirmation_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_package', to='sales_confirmation.salesconfirmationproposal'),
        ),
    ]
