# Generated by Django 5.1.2 on 2024-11-25 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0043_alter_salesconfirmationproposalpackage_sales_confirmation_proposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposalpackage',
            name='sales_confirmation_proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_package', to='sales_confirmation.salesconfirmationproposal'),
        ),
    ]
