# Generated by Django 5.1.2 on 2024-12-02 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0018_alter_salespackagespecies_amount'),
        ('sales', '0018_entityidentity'),
        ('sales_confirmation', '0044_alter_salesconfirmationproposalpackage_sales_confirmation_proposal'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesConfirmationCompanions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companions_set', to='sales.entity')),
                ('regulatory_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_companions_set', to='bm_hunting_settings.regulatoryhuntingpackage')),
                ('sales_confirmation_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companions', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Companions',
                'db_table': 'sales_confirmation_companions',
            },
        ),
        migrations.CreateModel(
            name='SalesConfirmationProposalCompanionItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('arrival', models.DateTimeField(blank=True, null=True)),
                ('charter_in', models.DateTimeField(blank=True, null=True)),
                ('charter_out', models.DateTimeField(blank=True, null=True)),
                ('hotel_booking', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_confirmation_proposal_companion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_itineraries', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Companion Itineraries',
                'db_table': 'companion_itinerary',
            },
        ),
        migrations.CreateModel(
            name='SalesConfirmationProposalObserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_proposal_observer_set', to='sales.entity')),
                ('sales_confirmation_proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observers', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Proposal Observers',
                'db_table': 'sales_confirmation_proposal_observer',
            },
        ),
    ]
