# Generated by Django 5.1.2 on 2024-12-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_entityidentity'),
        ('sales_confirmation', '0045_salesconfirmationcompanions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='airport_name',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='charter_in',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='charter_out',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='hotel_booking',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='sales_confirmation_proposal_companion',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='companion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companion_itineraries_set', to='sales.entity'),
        ),
        migrations.AddField(
            model_name='salesconfirmationproposalcompanionitinerary',
            name='itinarary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companion_itineraries', to='sales_confirmation.salesconfirmationproposalitinerary'),
        ),
        migrations.AlterModelTable(
            name='salesconfirmationproposalcompanionitinerary',
            table='sales_confirmation_companion_itinerary',
        ),
    ]
