# Generated by Django 5.1.2 on 2024-12-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0046_remove_salesconfirmationproposalcompanionitinerary_airport_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesconfirmationproposalcompanionitinerary',
            old_name='companion',
            new_name='entity',
        ),
    ]
