# Generated by Django 5.1.2 on 2024-12-02 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "sales_confirmation",
            "0047_rename_companion_salesconfirmationproposalcompanionitinerary_entity",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="entitycontactpermitdates",
            table="enity_contract_permit_dates",
        ),
    ]
