# Generated by Django 5.1.2 on 2024-12-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0048_alter_entitycontactpermitdates_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntityContactPermitDates',
            new_name='EntityContractPermitDates',
        ),
    ]
