# Generated by Django 5.1.2 on 2024-12-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_entityidentity'),
        ('sales_confirmation', '0049_rename_entitycontactpermitdates_entitycontractpermitdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesconfirmationcompanions',
            name='sales_confirmation_proposal',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationproposalobserver',
            name='sales_confirmation_proposal',
        ),
        migrations.AddField(
            model_name='salesconfirmationcompanions',
            name='sales_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companions_set', to='sales.salesinquiry'),
        ),
        migrations.AddField(
            model_name='salesconfirmationproposalobserver',
            name='sales_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observer_set', to='sales.salesinquiry'),
        ),
    ]
