# Generated by Django 5.1.2 on 2024-12-04 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0050_remove_salesconfirmationcompanions_sales_confirmation_proposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesconfirmationproposalpackage',
            name='hunting_license',
        ),
        migrations.AddField(
            model_name='salesconfirmationproposal',
            name='hunting_license',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)]),
        ),
    ]
