# Generated by Django 5.1.2 on 2024-12-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0018_alter_salespackagespecies_amount'),
        ('sales_confirmation', '0053_alter_gameactivity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotaspeciesstatus',
            name='quota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='species_sales_quota_status_set', to='bm_hunting_settings.quota'),
        ),
    ]
