# Generated by Django 5.1.2 on 2024-12-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0054_alter_salesquotaspeciesstatus_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationcontract',
            name='sales_confirmation_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_confirmation_contract_set', to='sales_confirmation.salesconfirmationproposal'),
        ),
    ]
