# Generated by Django 5.1.2 on 2024-12-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0055_alter_salesconfirmationcontract_sales_confirmation_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfirmationcontract',
            name='contractor_type',
            field=models.CharField(blank=True, choices=[('MAIN_HUNTER', 'Main Hunter'), ('COMPANION_HUNTER', 'Companion Hunter')], max_length=255, null=True),
        ),
    ]
