# Generated by Django 5.1.2 on 2024-12-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0030_safaryextras_amount'),
        ('sales_confirmation', '0056_salesconfirmationcontract_contractor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesConfirmationProposalSafaryExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('safary_extras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extras_set', to='bm_hunting_settings.safaryextras')),
                ('sales_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safary_extras_set', to='sales_confirmation.salesconfirmationproposal')),
            ],
            options={
                'verbose_name_plural': 'Sales Confirmation Safary Extras',
                'db_table': 'sales_confirmation_safary_extras',
            },
        ),
    ]
