# Generated by Django 5.1.2 on 2024-12-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0031_safaryextras_currency_salesitinerarypricelist'),
        ('sales_confirmation', '0057_salesconfirmationproposalsafaryextras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposalsafaryextras',
            name='safary_extras',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extras_set', to='bm_hunting_settings.safaryextras'),
        ),
        migrations.AlterField(
            model_name='salesconfirmationproposalsafaryextras',
            name='sales_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safary_extras_set', to='sales_confirmation.salesconfirmationproposal'),
        ),
    ]
