# Generated by Django 5.1.2 on 2024-12-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0035_safaryextras_charges_per'),
        ('sales_confirmation', '0059_salesconfirmationproposalsafaryextras_account'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesconfirmationproposalsafaryextras',
            unique_together={('safary_extras', 'sales_proposal')},
        ),
    ]
