# Generated by Django 5.1.2 on 2024-12-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0035_safaryextras_charges_per'),
        ('sales_confirmation', '0060_alter_salesconfirmationproposalsafaryextras_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesconfirmationproposalsafaryextras',
            old_name='safary_extras',
            new_name='safari_extras',
        ),
        migrations.AlterUniqueTogether(
            name='salesconfirmationproposalsafaryextras',
            unique_together={('safari_extras', 'sales_proposal')},
        ),
    ]
