# Generated by Django 5.1.2 on 2024-12-29 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_salesinquiry_season'),
        ('sales_confirmation', '0061_rename_safary_extras_salesconfirmationproposalsafaryextras_safari_extras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesconfirmationproposalsafaryextras',
            name='sales_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safary_extras_set', to='sales.salesinquiry'),
        ),
    ]
