# Generated by Django 5.1.2 on 2024-12-30 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0065_rename_address_accommodationaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationaddress',
            options={'verbose_name_plural': 'Accommodation Addresses'},
        ),
        migrations.AlterModelOptions(
            name='accommodationtype',
            options={'verbose_name_plural': 'Accommodation Types'},
        ),
        migrations.AlterModelTable(
            name='accommodationaddress',
            table='accommodation_address',
        ),
        migrations.AlterModelTable(
            name='accommodationtype',
            table='accommodation_type',
        ),
    ]
