# Generated by Django 5.1.2 on 2024-12-30 12:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0037_rename_seasons_salesitinerarypricelist_season'),
        ('sales_confirmation', '0066_alter_accommodationaddress_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationcost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationaccommodation',
            name='account',
        ),
        migrations.RemoveField(
            model_name='salesconfirmationaccommodation',
            name='total_acc_cost',
        ),
        migrations.AddField(
            model_name='accommodationcost',
            name='accommodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_cost_set', to='sales_confirmation.salesconfirmationaccommodation'),
        ),
        migrations.AddField(
            model_name='accommodationcost',
            name='account',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='accommodationcost',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='accommodationcost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='accommodationcost',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bm_hunting_settings.currency'),
        ),
    ]
