# Generated by Django 5.1.2 on 2024-12-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0067_remove_accommodationcost_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationcost',
            name='created_at',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
