# Generated by Django 5.1.2 on 2024-12-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0069_rename_cost_accommodationcost_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfirmationcompanions',
            name='charter_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesconfirmationcompanions',
            name='charter_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesconfirmationproposalobserver',
            name='charter_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesconfirmationproposalobserver',
            name='charter_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
