# Generated by Django 5.1.2 on 2024-12-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0070_salesconfirmationcompanions_charter_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesconfirmationcompanions',
            name='arrival_airport',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesconfirmationproposalobserver',
            name='arrival_airport',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
