# Generated by Django 5.1.2 on 2024-12-31 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bm_hunting_settings", "0038_delete_accommodationtype"),
        ("sales", "0025_remove_salesiquirypreference_accommodation_type"),
        (
            "sales_confirmation",
            "0071_salesconfirmationcompanions_arrival_airport_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesConfirmationChartersPriceList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "charters_price_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charters_price_list_set",
                        to="bm_hunting_settings.salesitinerarypricelist",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charters_price_list_set",
                        to="sales.entity",
                    ),
                ),
                (
                    "sales_inquiry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charters_price_list_set",
                        to="sales.salesinquiry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sales Confirmation Accommodation Charters Price List",
                "db_table": "sales_confirmation_charters_price_list",
            },
        ),
    ]
