# Generated by Django 5.1.2 on 2024-12-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_confirmation', '0072_salesconfirmationcharterspricelist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesconfirmationcharterspricelist',
            table='sales_confirmation_charters_price',
        ),
    ]
