# Generated by Django 5.0.4 on 2024-10-03 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Hunting Blocks',
                'db_table': 'bm_hunting_blocks',
            },
        ),
        migrations.CreateModel(
            name='HuntingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1x1', '1x1'), ('2x1', '2x1'), ('3x1', '3x1'), ('4x1', '4x1'), ('5x1', '5x1'), ('6x1', '6x1'), ('7x1', '7x1'), ('8x1', '8x1'), ('9x1', '9x1'), ('10x1', '10x1')], max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Hunting Types',
                'db_table': 'bm_hunting_types',
            },
        ),
        migrations.CreateModel(
            name='SafariPackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Regular', 'Regular Safari'), ('Premium', 'Premium Safari'), ('Major', 'Major Safari')], max_length=100)),
                ('safari_duration', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Safari Package Types',
                'db_table': 'bm_safari_package_types',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Species',
                'db_table': 'bm_species',
            },
        ),
        migrations.CreateModel(
            name='SafariPackageHuntingSpeciesLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunting_limit', models.IntegerField(default=0)),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits_species', to='bm_hunting_settings.safaripackagetype')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits_species', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Safari Package Hunting Species Limits',
                'db_table': 'bm_safari_package_hunting_species_limits',
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hunting_limit', models.IntegerField(default=0)),
                ('hunting_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='bm_hunting_settings.huntingblock')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Quotas',
                'db_table': 'bm_quotas',
            },
        ),
        migrations.CreateModel(
            name='BushmanHuntingScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunting_limit', models.IntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bushman_hunting_scope', to='bm_hunting_settings.huntingblock')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bushman_hunting_scope', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Bushman Hunting Scopes',
                'db_table': 'bm_bushman_hunting_scopes',
            },
        ),
    ]
