# Generated by Django 4.2.9 on 2024-10-24 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='huntingpackagecompanionshunter',
            table='hunting_package_companions_hunter_cost',
        ),
        migrations.CreateModel(
            name='HuntingPackageOberverHunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hunting_price_list_type_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_package_oberver_hunter', to='bm_hunting_settings.huntingpricetypepackage')),
            ],
            options={
                'verbose_name_plural': 'Hunting Package Oberver Hunter',
                'db_table': 'hunting_package_oberver_hunter_cost',
            },
        ),
    ]
