# Generated by Django 5.0.4 on 2024-10-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bushmanhuntingscope',
            table='bushman_hunting_scopes',
        ),
        migrations.AlterModelTable(
            name='huntingblock',
            table='hunting_blocks',
        ),
        migrations.AlterModelTable(
            name='huntingtype',
            table='hunting_types',
        ),
        migrations.AlterModelTable(
            name='quota',
            table='quotas',
        ),
        migrations.AlterModelTable(
            name='safaripackagehuntingspecieslimit',
            table='safari_package_hunting_species_limits',
        ),
        migrations.AlterModelTable(
            name='safaripackagetype',
            table='safari_package_types',
        ),
        migrations.AlterModelTable(
            name='species',
            table='species',
        ),
    ]
