# Generated by Django 5.0.4 on 2024-10-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0002_alter_bushmanhuntingscope_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingblock',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='huntingblock',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='hunting_block',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='hunting_limit',
        ),
        migrations.RemoveField(
            model_name='quota',
            name='species',
        ),
        migrations.AddField(
            model_name='huntingblock',
            name='adress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='huntingblock',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huntingblock',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='huntingblock',
            name='qouta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_blocks', to='bm_hunting_settings.quota'),
        ),
        migrations.AddField(
            model_name='huntingblock',
            name='species',
            field=models.ManyToManyField(to='bm_hunting_settings.species'),
        ),
        migrations.CreateModel(
            name='HuntingSpeciesLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hunting_limit', models.IntegerField(default=0)),
                ('hunting_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits_species', to='bm_hunting_settings.huntingblock')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits_species', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Safari Package Hunting Species Limits',
                'db_table': 'safari_package_hunting_species_limits',
            },
        ),
        migrations.DeleteModel(
            name='SafariPackageHuntingSpeciesLimit',
        ),
    ]
