# Generated by Django 5.0.4 on 2024-10-03 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0003_remove_huntingblock_end_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HuntingSpeciesLimit',
            new_name='BlockHuntingSpeciesLimit',
        ),
        migrations.AddField(
            model_name='huntingtype',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='huntingblock',
            name='qouta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_blocks', to='bm_hunting_settings.quota'),
        ),
        migrations.AlterModelTable(
            name='blockhuntingspecieslimit',
            table=None,
        ),
        migrations.DeleteModel(
            name='BushmanHuntingScope',
        ),
    ]
