# Generated by Django 5.0.4 on 2024-10-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0004_rename_huntingspecieslimit_blockhuntingspecieslimit_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blockhuntingspecieslimit',
            table='block_hunting_species_limits',
        ),
    ]
