# Generated by Django 4.2.9 on 2024-10-26 07:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0004_alter_huntingpricetypepackage_price_list_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotaSpeciesStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provission_sales', 'Provission Sales'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=100)),
                ('quatity', models.IntegerField(default=0)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_sales_quota_status_set', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Sales Quota Species Status',
                'db_table': 'sales_quota_species_status',
            },
        ),
    ]
