# Generated by Django 4.2.9 on 2024-10-26 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0005_salesquotaspeciesstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotaspeciesstatus',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provision_sales', 'Provision Sales'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=100),
        ),
    ]
