# Generated by Django 4.2.9 on 2024-10-26 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0006_alter_salesquotaspeciesstatus_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesQuotaSpeciesStatus',
        ),
    ]
