# Generated by Django 4.2.9 on 2024-10-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0007_delete_salesquotaspeciesstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatoryhuntingpackagespecies',
            name='r_hunting_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_hunting_package_set', to='bm_hunting_settings.regulatoryhuntingpackage'),
        ),
        migrations.AlterField(
            model_name='regulatoryhuntingpackagespecies',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_hunting_package_species_set', to='bm_hunting_settings.species'),
        ),
    ]
