# Generated by Django 5.0.4 on 2024-10-03 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0008_remove_package_end_date_remove_package_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanionHunterCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Companion Hunter Cost',
                'db_table': 'companion_hunter_cost',
            },
        ),
        migrations.AddField(
            model_name='safaripackagetype',
            name='Species',
            field=models.ManyToManyField(related_name='safari_species', to='bm_hunting_settings.species'),
        ),
        migrations.AddField(
            model_name='safaripackagetype',
            name='hunting_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_type', to='bm_hunting_settings.safaripackagetype'),
        ),
    ]
