# Generated by Django 4.2.9 on 2024-10-28 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0009_huntingpackagecustomization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingpackagecustomization',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='huntingpackagecustomization',
            name='name',
        ),
    ]
