# Generated by Django 4.2.9 on 2024-10-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0010_remove_huntingpackagecustomization_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingpackagecustomization',
            name='description',
        ),
    ]
