# Generated by Django 5.0.4 on 2024-10-03 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0010_remove_package_number_of_safari_spots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='professional_hunter_cost',
            new_name='baiting_vehicle_with_PH_cost',
        ),
    ]
