# Generated by Django 5.0.4 on 2024-10-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0011_rename_professional_hunter_cost_package_baiting_vehicle_with_ph_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='hunting_species',
        ),
        migrations.AddField(
            model_name='package',
            name='species',
            field=models.ManyToManyField(related_name='package_species_list', to='bm_hunting_settings.speciesavailabilityandcost'),
        ),
        migrations.DeleteModel(
            name='SalesPackageHuntingSpecies',
        ),
    ]
