# Generated by Django 4.2.9 on 2024-10-28 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0012_alter_regulatoryhuntingpackage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulatoryhuntingpackage',
            options={'verbose_name_plural': 'Safari Package'},
        ),
    ]
