# Generated by Django 5.0.4 on 2024-10-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0012_remove_package_hunting_species_package_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesavailabilityandcost',
            name='availability',
        ),
        migrations.AddField(
            model_name='speciesavailabilityandcost',
            name='available_in_block',
            field=models.IntegerField(blank=True, choices=[('MS', 'MS'), ('BK', 'BK'), ('MS_BK', 'MS, BK')], null=True),
        ),
    ]
