# Generated by Django 5.0.4 on 2024-10-04 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0013_remove_speciesavailabilityandcost_availability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='trophy_fees_list',
        ),
    ]
