# Generated by Django 4.2.9 on 2024-10-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0014_remove_package_trophy_fees_list'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blockhuntingspecieslimit',
            table='species_unit',
        ),
    ]
