# Generated by Django 5.1.2 on 2024-11-02 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0015_huntingpackagecompanionshunter_created_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='huntingpackagecompanionshunter',
            unique_together=set(),
        ),
    ]
