# Generated by Django 5.1.2 on 2024-11-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0016_alter_huntingpackagecompanionshunter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingpackagecompanionshunter',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='huntingpackageoberverhunter',
            name='days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
