# Generated by Django 4.2.9 on 2024-10-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0016_rename_species_safaripackagetype_species'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlockHuntingSpeciesLimit',
            new_name='HuntingBlockSpeciesLimit',
        ),
    ]
