# Generated by Django 4.2.9 on 2024-10-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0017_rename_blockhuntingspecieslimit_huntingblockspecieslimit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='huntingblockspecieslimit',
            table=None,
        ),
    ]
