# Generated by Django 5.1.2 on 2024-11-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0017_alter_huntingpackagecompanionshunter_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespackagespecies',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
