# Generated by Django 5.1.2 on 2024-12-19 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0018_alter_salespackagespecies_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespackages',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_area_sales_packages', to='bm_hunting_settings.huntingarea'),
        ),
    ]
