# Generated by Django 5.1.2 on 2024-12-19 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0019_salespackages_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingpricelist',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_price_list', to='bm_hunting_settings.huntingarea'),
        ),
    ]
