# Generated by Django 5.1.2 on 2024-12-19 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0020_alter_huntingpricelist_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespackages',
            name='regulatory_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_hunting_package_sales_packages', to='bm_hunting_settings.regulatoryhuntingpackage'),
        ),
    ]
