# Generated by Django 4.2.9 on 2024-10-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0022_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingtype',
            name='name',
            field=models.CharField(choices=[('1x1', '1x1'), ('2x1', '2x1'), ('3x1', '3x1'), ('4x1', '4x1'), ('5x1', '5x1'), ('6x1', '6x1'), ('7x1', '7x1'), ('8x1', '8x1'), ('9x1', '9x1'), ('10x1', '10x1')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='packagetype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='safaripackagetype',
            name='name',
            field=models.CharField(choices=[('Regular', 'Regular Safari'), ('Premium', 'Premium Safari'), ('Major', 'Major Safari')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='trophyfees',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='packagetype',
            table='gev_',
        ),
    ]
