# Generated by Django 5.1.2 on 2024-12-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0022_alter_huntingtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespackages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='salespackages',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
