# Generated by Django 4.2.9 on 2024-10-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0023_alter_huntingtype_name_alter_packagetype_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='packagetype',
            table='package_types',
        ),
    ]
