# Generated by Django 5.1.2 on 2024-12-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0023_salespackages_created_at_salespackages_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('descriptions', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Unit of Measurements',
                'db_table': 'unit_of_measurements',
            },
        ),
    ]
