# Generated by Django 5.1.2 on 2024-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0024_unitofmeasurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingpackagecompanionshunter',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='huntingpackageoberverhunter',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
