# Generated by Django 4.2.9 on 2024-10-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0025_alter_quota_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quota',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
