# Generated by Django 5.1.2 on 2024-12-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0026_species_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='type',
            field=models.CharField(blank=True, choices=[('MAIN', 'Main Species'), ('NORMAL', 'Normal Species')], default='NORMAL', max_length=100, null=True),
        ),
    ]
