# Generated by Django 4.2.9 on 2024-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0027_quota_create_at_quota_update_at_quota_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationalities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Nationalities',
                'db_table': 'nationalities',
            },
        ),
    ]
