# Generated by Django 5.1.2 on 2024-12-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0028_seasons_end_at_seasons_start_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafaryExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Safary Extras',
                'db_table': 'safary_extras',
            },
        ),
    ]
