# Generated by Django 4.2.9 on 2024-10-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0028_nationalities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nationalities',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
