# Generated by Django 4.2.9 on 2024-10-09 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0029_alter_nationalities_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='package',
            name='hunting_block',
        ),
        migrations.RemoveField(
            model_name='package',
            name='hunting_type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='species',
        ),
        migrations.RemoveField(
            model_name='speciesavailabilityandcost',
            name='hunting_block',
        ),
        migrations.RemoveField(
            model_name='speciesavailabilityandcost',
            name='species',
        ),
        migrations.RemoveField(
            model_name='huntingblockspecieslimit',
            name='hunting_block',
        ),
        migrations.DeleteModel(
            name='HuntingBlock',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='SpeciesAvailabilityAndCost',
        ),
    ]
