# Generated by Django 5.1.2 on 2024-12-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0029_safaryextras'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaryextras',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
