# Generated by Django 5.1.2 on 2024-12-28 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0030_safaryextras_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaryextras',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safary_extras_currency_set', to='bm_hunting_settings.currency'),
        ),
        migrations.CreateModel(
            name='SalesItineraryPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salestinerary_price_list_currency_set', to='bm_hunting_settings.currency')),
            ],
            options={
                'verbose_name_plural': 'Sales Itinary',
                'db_table': 'sales_itinary',
            },
        ),
    ]
