# Generated by Django 4.2.9 on 2024-10-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0030_remove_package_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HuntingBlockSpeciesLimit',
        ),
    ]
