# Generated by Django 5.1.2 on 2024-12-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0031_safaryextras_currency_salesitinerarypricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='safaryextras',
            name='seasons',
            field=models.ManyToManyField(blank=True, related_name='safary_extras_season_set', to='bm_hunting_settings.seasons'),
        ),
    ]
