# Generated by Django 4.2.9 on 2024-10-09 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0031_delete_huntingblockspecieslimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoLocationCoordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_type', models.CharField(blank=True, max_length=100, null=True)),
                ('coordinates', models.JSONField(default=list)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('satilate', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Geo Location Coordinates',
                'db_table': 'geo_location_coordinates',
            },
        ),
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Location Types',
                'db_table': 'location_types',
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Operation Types',
                'db_table': 'operation_types',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_disabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('geo_coordinates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geo_coordinates', to='bm_hunting_settings.geolocationcoordinates')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_type', to='bm_hunting_settings.locationtype')),
            ],
            options={
                'verbose_name_plural': 'Locations',
                'db_table': 'locations',
            },
        ),
    ]
