# Generated by Django 4.2.9 on 2024-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0032_geolocationcoordinates_locationtype_operationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
