# Generated by Django 5.1.2 on 2024-12-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0032_safaryextras_seasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='safaryextras',
            old_name='seasons',
            new_name='season',
        ),
    ]
