# Generated by Django 4.2.9 on 2024-10-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0033_species_scientific_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesUnis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_unis', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Species Unis',
                'db_table': 'species_unis',
            },
        ),
    ]
