# Generated by Django 4.2.9 on 2024-10-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0034_speciesunis'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quota',
            table='hunting_quotas',
        ),
    ]
