# Generated by Django 5.1.2 on 2024-12-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0035_safaryextras_charges_per'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitinerarypricelist',
            name='seasons',
            field=models.ManyToManyField(related_name='salestinerary_price_list_season_set', to='bm_hunting_settings.seasons'),
        ),
    ]
