# Generated by Django 4.2.9 on 2024-10-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0035_alter_quota_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_areas', to='bm_hunting_settings.locations')),
                ('qouta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_blocks', to='bm_hunting_settings.quota')),
                ('species', models.ManyToManyField(to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Hunting Blocks',
                'db_table': 'hunting_areas',
            },
        ),
        migrations.CreateModel(
            name='HuntingQuatasArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_quatas_area', to='bm_hunting_settings.huntingarea')),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_quatas_area', to='bm_hunting_settings.quota')),
            ],
            options={
                'verbose_name_plural': 'Hunting Quatas Area',
                'db_table': 'hunting_quatas_area',
            },
        ),
    ]
