# Generated by Django 4.2.9 on 2024-10-09 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0036_huntingarea_huntingquatasarea'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaHutingSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('quota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_hunting_species', to='bm_hunting_settings.quota')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_hunting_species', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Quota Hunting Species',
                'db_table': 'quota_hunting_species',
            },
        ),
    ]
