# Generated by Django 5.1.2 on 2024-12-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0036_salesitinerarypricelist_seasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesitinerarypricelist',
            old_name='seasons',
            new_name='season',
        ),
    ]
