# Generated by Django 5.1.2 on 2024-12-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0037_rename_seasons_salesitinerarypricelist_season'),
        ('sales', '0025_remove_salesiquirypreference_accommodation_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccommodationType',
        ),
    ]
