# Generated by Django 5.1.2 on 2024-12-31 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0038_delete_accommodationtype'),
        ('sales_confirmation', '0072_salesconfirmationcharterspricelist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesItineraryPriceList',
            new_name='SalesChartersPriceList',
        ),
    ]
