# Generated by Django 4.2.9 on 2024-10-09 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0039_rename_countries_country'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
    ]
