# Generated by Django 4.2.9 on 2024-10-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0041_alter_country_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='Country',
        ),
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
