# Generated by Django 5.1.2 on 2024-12-31 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0042_rename_salesitinerarypricelist_salescharterspricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salescharterspricelist',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salestinerary_price_list_currency_set', to='bm_hunting_settings.currency'),
        ),
        migrations.RemoveField(
            model_name='salescharterspricelist',
            name='season',
        ),
        migrations.AddField(
            model_name='salescharterspricelist',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salestinerary_price_list_season_set', to='bm_hunting_settings.seasons'),
        ),
    ]
