# Generated by Django 4.2.9 on 2024-10-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0045_alter_speciesunits_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingarea',
            name='species',
        ),
    ]
