# Generated by Django 4.2.9 on 2024-10-11 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0046_remove_huntingarea_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntingarea',
            name='species',
            field=models.ManyToManyField(to='bm_hunting_settings.species'),
        ),
    ]
