# Generated by Django 4.2.9 on 2024-10-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0047_huntingarea_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingarea',
            name='species',
        ),
    ]
