# Generated by Django 4.2.9 on 2024-10-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0048_remove_huntingarea_species'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuotaHutingSpecies',
            new_name='QuotaHutingAreaSpecies',
        ),
    ]
