# Generated by Django 4.2.9 on 2024-10-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0049_rename_quotahutingspecies_quotahutingareaspecies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingarea',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_areas', to='bm_hunting_settings.locations'),
        ),
    ]
