# Generated by Django 4.2.9 on 2024-10-11 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0050_alter_huntingarea_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotahutingareaspecies',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quota_hunting_species', to='bm_hunting_settings.huntingarea'),
        ),
    ]
