# Generated by Django 4.2.9 on 2024-10-11 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0051_quotahutingareaspecies_area'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quotahutingareaspecies',
            table='quota_hunting_area_species',
        ),
    ]
