# Generated by Django 4.2.9 on 2024-10-11 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0052_alter_quotahutingareaspecies_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingarea',
            name='qouta',
        ),
    ]
