# Generated by Django 4.2.9 on 2024-10-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0053_remove_huntingarea_qouta'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='huntingquatasarea',
            unique_together={('area', 'quota')},
        ),
        migrations.AlterUniqueTogether(
            name='quotahutingareaspecies',
            unique_together={('species', 'area')},
        ),
    ]
