# Generated by Django 4.2.9 on 2024-10-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0054_alter_huntingquatasarea_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='huntingarea',
            options={'verbose_name_plural': 'Hunting Area'},
        ),
    ]
