# Generated by Django 4.2.9 on 2024-10-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0055_alter_huntingarea_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotahutingareaspecies',
            unique_together={('species', 'area', 'quota')},
        ),
    ]
