# Generated by Django 4.2.9 on 2024-10-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0056_alter_quotahutingareaspecies_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SafariPackageType',
            new_name='RegulatoryHuntingpackage',
        ),
    ]
