# Generated by Django 4.2.9 on 2024-10-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0057_rename_safaripackagetype_regulatoryhuntingpackage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='regulatoryhuntingpackage',
            table='regulatory_hunting_packages',
        ),
    ]
