# Generated by Django 4.2.9 on 2024-10-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0058_alter_regulatoryhuntingpackage_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryhuntingpackage',
            name='species',
        ),
    ]
