# Generated by Django 4.2.9 on 2024-10-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0059_remove_regulatoryhuntingpackage_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulatoryhuntingpackage',
            old_name='safari_duration',
            new_name='duration',
        ),
    ]
