# Generated by Django 4.2.9 on 2024-10-15 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bm_hunting_settings', '0060_rename_safari_duration_regulatoryhuntingpackage_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatoryhuntingpackage',
            name='hunting_limit',
        ),
        migrations.AddField(
            model_name='regulatoryhuntingpackage',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryhuntingpackage',
            name='quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_hunting_packages', to='bm_hunting_settings.quota'),
        ),
        migrations.AddField(
            model_name='regulatoryhuntingpackage',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='regulatoryhuntingpackage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_regulatory_hunting_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
