# Generated by Django 4.2.9 on 2024-10-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0061_remove_regulatoryhuntingpackage_hunting_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryHuntingPackageSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('r_hunting_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_hunting_package_species', to='bm_hunting_settings.regulatoryhuntingpackage')),
                ('session_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regulatory_hunting_package_species', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Regulatory Hunting Package Species',
                'db_table': 'regulatory_hunting_package_species',
            },
        ),
    ]
