# Generated by Django 4.2.9 on 2024-10-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0062_regulatoryhuntingpackagespecies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regulatoryhuntingpackagespecies',
            old_name='session_species',
            new_name='species',
        ),
    ]
