# Generated by Django 4.2.9 on 2024-10-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0063_rename_session_species_regulatoryhuntingpackagespecies_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatoryhuntingpackage',
            name='name',
            field=models.CharField(choices=[('Regular', 'Regular Safari'), ('Premium', 'Premium Safari'), ('Major', 'Major Safari')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='regulatoryhuntingpackage',
            unique_together={('quota', 'name')},
        ),
    ]
