# Generated by Django 4.2.9 on 2024-10-15 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0064_alter_regulatoryhuntingpackage_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='location_id',
            new_name='location',
        ),
    ]
