# Generated by Django 4.2.9 on 2024-10-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0065_rename_location_id_locations_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geolocationcoordinates',
            old_name='point_type',
            new_name='coordinates_type',
        ),
        migrations.RemoveField(
            model_name='geolocationcoordinates',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='geolocationcoordinates',
            name='satilate',
        ),
    ]
