# Generated by Django 4.2.9 on 2024-10-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0066_rename_point_type_geolocationcoordinates_coordinates_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocationcoordinates',
            name='coordinates_type',
            field=models.CharField(blank=True, choices=[('Point', 'Point'), ('LineString', 'LineString'), ('Polygon', 'Polygon'), ('MultiPoint', 'MultiPoint'), ('MultiLineString', 'MultiLineString'), ('MultiPolygon', 'MultiPolygon')], max_length=100, null=True),
        ),
    ]
