# Generated by Django 4.2.9 on 2024-10-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0067_alter_geolocationcoordinates_coordinates_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocationcoordinates',
            name='coordinates_type',
            field=models.CharField(blank=True, choices=[('Point', 'Point'), ('LineString', 'LineString'), ('Polygon', 'Polygon'), ('MultiPoint', 'MultiPoint'), ('MultiLineString', 'MultiLineString'), ('MultiPolygon', 'MultiPolygon')], default='Point', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='location_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_type', to='bm_hunting_settings.locationtype'),
        ),
    ]
