# Generated by Django 4.2.9 on 2024-10-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0068_alter_geolocationcoordinates_coordinates_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locations',
            old_name='location',
            new_name='id',
        ),
    ]
