# Generated by Django 4.2.9 on 2024-10-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0069_rename_location_locations_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
