# Generated by Django 4.2.9 on 2024-10-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0070_alter_locations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntingarea',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
