# Generated by Django 4.2.9 on 2024-10-16 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0071_alter_huntingarea_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='huntingtype',
            name='price',
        ),
    ]
