# Generated by Django 4.2.9 on 2024-10-16 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bm_hunting_settings', '0072_remove_huntingtype_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_price_list', to='bm_hunting_settings.huntingarea')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_hunting_price_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Hunting Price List',
                'db_table': 'hunting_price_list',
                'unique_together': {('area', 'start_date', 'end_date')},
            },
        ),
    ]
