# Generated by Django 4.2.9 on 2024-10-16 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0073_huntingpricelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='huntingpricelist',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='huntingpricelist',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
