# Generated by Django 4.2.9 on 2024-10-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0074_huntingpricelist_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingPriceListType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_price_list_type', to='bm_hunting_settings.currency')),
                ('huting_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_price_list_type', to='bm_hunting_settings.huntingtype')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_price_list_type', to='bm_hunting_settings.huntingpricelist')),
            ],
            options={
                'verbose_name_plural': 'Hunting Price List Type',
                'db_table': 'hunting_price_list_type',
                'unique_together': {('price_list', 'amount', 'currency')},
            },
        ),
    ]
