# Generated by Django 4.2.9 on 2024-10-16 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0076_alter_huntingpricelisttype_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salespackage',
            name='sales_quota',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_packages', to='bm_hunting_settings.quota'),
        ),
        migrations.CreateModel(
            name='salesPackageSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_package_species', to='bm_hunting_settings.currency')),
                ('sales_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_package_species', to='bm_hunting_settings.salespackage')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_package_species', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Sales Package Species',
                'db_table': 'sales_package_species',
                'unique_together': {('sales_package', 'species')},
            },
        ),
    ]
