# Generated by Django 4.2.9 on 2024-10-16 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0077_salespackage_sales_quota_salespackagespecies'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_model', models.CharField(choices=[('per_person', 'Per Person'), ('daily', 'Daily'), ('round', 'Round')], max_length=100)),
                ('cost_use_case', models.CharField(choices=[('person', 'Person'), ('hunter', 'Hunter')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Additional Services',
                'db_table': 'additional_services',
            },
        ),
        migrations.CreateModel(
            name='HuntingPackageUpgradeFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_package_upgrade_fees', to='bm_hunting_settings.currency')),
                ('huting_price_list_type_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_package_upgrade_fees', to='bm_hunting_settings.huntingpricetypepackage')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_package_upgrade_fees', to='bm_hunting_settings.species')),
            ],
            options={
                'verbose_name_plural': 'Hunting Package Upgrade Fees',
                'db_table': 'hunting_package_upgrade_fees',
            },
        ),
        migrations.CreateModel(
            name='HuntingPackageCompanionsHunter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.IntegerField(default=0)),
                ('amont', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hunting_price_list_type_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hunting_package_companions_hunter', to='bm_hunting_settings.huntingpricetypepackage')),
            ],
            options={
                'verbose_name_plural': 'Hunting Package Companions Hunter',
                'db_table': 'hunting_package_companions_hunter',
            },
        ),
    ]
