# Generated by Django 4.2.9 on 2024-10-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0078_additionalservices_huntingpackageupgradefees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huntingpackagecompanionshunter',
            old_name='amont',
            new_name='amount',
        ),
    ]
