# Generated by Django 4.2.9 on 2024-10-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0080_delete_packagetype_delete_trophyfees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanionHunterCost',
        ),
    ]
