# Generated by Django 4.2.9 on 2024-10-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0081_delete_companionhuntercost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huntingpricelisttype',
            old_name='huting_type',
            new_name='hunting_type',
        ),
        migrations.AlterUniqueTogether(
            name='huntingpricelisttype',
            unique_together={('price_list', 'hunting_type')},
        ),
    ]
