# Generated by Django 4.2.9 on 2024-10-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0083_alter_huntingpricelist_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salespackagespecies',
            name='currency',
        ),
    ]
