# Generated by Django 4.2.9 on 2024-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0084_remove_salespackagespecies_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salespackage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
