# Generated by Django 4.2.9 on 2024-10-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0087_alter_species_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
