from django.contrib import admin

from . import models

admin.site.register(models.Quota)
admin.site.register(models.Nationalities)
admin.site.register(models.Species)
admin.site.register(models.HuntingArea)
admin.site.register(models.HuntingQuatasArea)
admin.site.register(models.QuotaHuntingAreaSpecies)
admin.site.register(models.RegulatoryHuntingpackage)
admin.site.register(models.RegulatoryHuntingPackageSpecies)
admin.site.register(models.GeoLocationCoordinates)
admin.site.register(models.Locations)
admin.site.register(models.SalesPackages)
admin.site.register(models.HuntingPriceList)
admin.site.register(models.HuntingPriceTypePackage)
admin.site.register(models.HuntingPackageCompanionsHunter)
admin.site.register(models.SalesPackageSpecies)
admin.site.register(models.HuntingPackageUpgradeFees)
admin.site.register(models.HuntingType)
admin.site.register(models.HuntingPriceListType)
admin.site.register(models.Currency)
admin.site.register(models.Seasons)
admin.site.register(models.HuntingPackageOberverHunter)
admin.site.register(models.HuntingPackageCustomization)
admin.site.register(models.HuntingPackageCustomizedSpecies)
admin.site.register(models.UnitOfMeasurements)
