from sales.models import EntityCategories
from rest_framework import viewsets
from sales.serializers.global_serializers import EntityCategoriesSerializer
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
