# Generated by Django 4.2.9 on 2024-10-07 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entitycategories',
            old_name='category_name',
            new_name='name',
        ),
    ]
