# Generated by Django 4.2.9 on 2024-10-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacts',
            table=None,
        ),
    ]
