# Generated by Django 4.2.9 on 2024-10-23 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_contacts_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacts',
            table='contacts',
        ),
    ]
