# Generated by Django 4.2.9 on 2024-10-08 09:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_contracttype_salespayment_salesconfirmation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_calender_sale_set', to='sales.salesconfirmation')),
            ],
            options={
                'verbose_name_plural': 'Sales Calenders',
                'db_table': 'sales_calenders',
            },
        ),
    ]
