# Generated by Django 4.2.9 on 2024-10-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_client_document_enity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Passport_Copy', 'Travel Packet(Passport Copy)'), ('Passport_Photo', 'Travel Packet(Passport  Photo'), ('Visa', 'Visa'), ('Gun Permits', 'Gun Permits'), ('CITES Documentation', 'CITES Documentation')], max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='forWho',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_type_set', to='sales.doctype'),
        ),
    ]
