# Generated by Django 4.2.9 on 2024-10-08 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0019_alter_huntingblockspecieslimit_table'),
        ('sales', '0004_salescalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagecustomization',
            name='hunting_block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizable_packages_set', to='bm_hunting_settings.huntingblock'),
        ),
        migrations.AddField(
            model_name='packagecustomization',
            name='hunting_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customizable_packages_set', to='bm_hunting_settings.huntingtype'),
        ),
        migrations.AddField(
            model_name='salescalender',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salescalender',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packagecustomization',
            name='number_of_hunters',
            field=models.IntegerField(default=1),
        ),
    ]
