# Generated by Django 4.2.9 on 2024-10-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_doctype_alter_document_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctype',
            options={'verbose_name_plural': 'Document Types'},
        ),
        migrations.AlterField(
            model_name='doctype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='doctype',
            table='doc_types',
        ),
    ]
