# Generated by Django 4.2.9 on 2024-10-08 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_packagecustomization_hunting_block_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forWho', models.CharField(max_length=100, null=True)),
                ('document_type', models.CharField(choices=[('Passport_Copy', 'Travel Packet(Passport Copy)'), ('Passport_Photo', 'Travel Packet(Passport  Photo'), ('Visa', 'Visa'), ('Gun Permits', 'Gun Permits'), ('CITES Documentation', 'CITES Documentation')], max_length=100)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_document_set', to='sales.entity')),
            ],
            options={
                'verbose_name_plural': 'Client Documents',
                'db_table': 'documents',
                'unique_together': {('forWho', 'document_type')},
            },
        ),
    ]
