# Generated by Django 4.2.9 on 2024-10-08 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_document'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entityhuntinginfos',
            table='hunting_infos',
        ),
    ]
