# Generated by Django 4.2.9 on 2024-10-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_doctype_options_alter_doctype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctype',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
