# Generated by Django 4.2.9 on 2024-10-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_doctype_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': ' Documents'},
        ),
    ]
