# Generated by Django 4.2.9 on 2024-10-26 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_salesquotaspeciesstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesquotaspeciesstatus',
            old_name='quata',
            new_name='quota',
        ),
    ]
