# Generated by Django 4.2.9 on 2024-10-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_rename_quata_salesquotaspeciesstatus_quota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesquotaspeciesstatus',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
