# Generated by Django 4.2.9 on 2024-10-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_entity_user_salesinquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='entity',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
