# Generated by Django 4.2.9 on 2024-10-27 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_rename_quatity_salesquotaspeciesstatus_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesQuotaSpeciesStatus',
        ),
    ]
