# Generated by Django 4.2.9 on 2024-10-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_entity_address_remove_entity_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiry',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
