# Generated by Django 4.2.9 on 2024-10-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_delete_salesquotaspeciesstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('id_proof', 'ID Proof'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('visa', 'Visa'), ('other', 'Other'), ('contract', 'Contract'), ('payment_receipt', 'Payment Receipt')], max_length=100, null=True),
        ),
    ]
