# Generated by Django 4.2.9 on 2024-10-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_salesinquiry_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='nationality_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
