# Generated by Django 4.2.9 on 2024-10-29 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_document_doc_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='enity',
            new_name='entity',
        ),
    ]
