# Generated by Django 4.2.9 on 2024-10-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0029_alter_nationalities_name'),
        ('sales', '0013_entity_nationality_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='hunting_area',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='hunting_type',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='safari_package_type',
        ),
        migrations.RemoveField(
            model_name='entityhuntinginfos',
            name='species_to_hunt',
        ),
        migrations.RemoveField(
            model_name='salescalender',
            name='sale_id',
        ),
        migrations.RemoveField(
            model_name='salesconfirmation',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='salesconfirmation',
            name='hunting_info',
        ),
        migrations.RemoveField(
            model_name='salesconfirmation',
            name='payment_id',
        ),
        migrations.AlterField(
            model_name='entity',
            name='nationality_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bm_hunting_settings.nationalities'),
        ),
        migrations.DeleteModel(
            name='Contract',
        ),
        migrations.DeleteModel(
            name='EntityHuntingInfos',
        ),
        migrations.DeleteModel(
            name='SalesCalender',
        ),
        migrations.DeleteModel(
            name='SalesConfirmation',
        ),
    ]
