# Generated by Django 4.2.9 on 2024-10-09 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_entityhuntinginfos_entity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesIquiryPreferece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preffered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_of_hunters', models.IntegerField(default=1)),
                ('no_of_observers', models.IntegerField(default=0)),
                ('no_of_days', models.IntegerField(default=0)),
                ('no_of_companions', models.IntegerField(default=0)),
                ('Special_requests', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_estimation', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('accommodation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sales_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiry_preference_set', to='sales.salesinquiry')),
            ],
            options={
                'verbose_name_plural': 'Sales Inquiry Preferences',
                'db_table': 'sales_inquiry_preferences',
            },
        ),
    ]
