# Generated by Django 4.2.9 on 2024-10-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_rename_enity_document_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesiquirypreference',
            name='no_of_companions',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesiquirypreference',
            name='no_of_observers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
