# Generated by Django 4.2.9 on 2024-10-09 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_salesiquirypreferece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageupgrade',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='packageupgrade',
            name='package',
        ),
        migrations.RemoveField(
            model_name='packageupgrade',
            name='species_to_hunt',
        ),
        migrations.DeleteModel(
            name='PackageCustomization',
        ),
        migrations.DeleteModel(
            name='PackageUpgrade',
        ),
    ]
