# Generated by Django 4.2.9 on 2024-10-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_packageupgrade_entity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='nationality',
        ),
    ]
