# Generated by Django 5.1.2 on 2024-11-14 06:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0017_alter_huntingpackagecompanionshunter_days_and_more'),
        ('sales', '0017_alter_entitycategory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_number', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_identity_set', to='sales.entity')),
                ('identity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_identity_type_set', to='bm_hunting_settings.identitytype')),
            ],
            options={
                'verbose_name_plural': 'Entity Identities',
                'db_table': 'entity_identities',
            },
        ),
    ]
