# Generated by Django 4.2.9 on 2024-10-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_remove_entity_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesiquirypreferece',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('Camping', 'Camping'), ('Hunting', 'Hunting'), ('residential', 'Residential'), ('Both', 'Both')], max_length=100, null=True),
        ),
    ]
