# Generated by Django 5.1.2 on 2024-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_entityidentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesiquirypreference',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesiquirypreference',
            name='hunting_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesiquirypreference',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
