# Generated by Django 4.2.9 on 2024-10-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_salesiquirypreferece_accommodation_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesIquiryPreferece',
            new_name='SalesIquiryPreference',
        ),
    ]
