# Generated by Django 5.1.2 on 2024-12-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_salesiquirypreference_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesiquirypreference',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='salesiquirypreference',
            name='start_time',
        ),
        migrations.AddField(
            model_name='salesiquirypreference',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesiquirypreference',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
