# Generated by Django 4.2.9 on 2024-10-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_rename_salesiquirypreferece_salesiquirypreference'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesiquirypreference',
            table=None,
        ),
    ]
