# Generated by Django 4.2.9 on 2024-10-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_salesiquirypreference_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salesiquirypreference',
            table='sales_inquiry_preferences',
        ),
    ]
