# Generated by Django 5.1.2 on 2024-12-20 12:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_remove_salesiquirypreference_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInquiryPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list', models.CharField(blank=True, max_length=100, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sales_inquiry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiry_price_list_set', to='sales.salesinquiry')),
            ],
            options={
                'verbose_name_plural': 'Sales Inquiry Price Lists',
                'db_table': 'sales_inquiry_price_lists',
            },
        ),
    ]
