# Generated by Django 4.2.9 on 2024-10-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_salesiquirypreference_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='nationality_id',
            new_name='nationality',
        ),
    ]
