# Generated by Django 5.1.2 on 2024-12-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0023_salespackages_created_at_salespackages_updated_at'),
        ('sales', '0021_salesinquirypricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinquirypricelist',
            name='price_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiry_price_list_set', to='bm_hunting_settings.huntingpricelist'),
        ),
    ]
