# Generated by Django 5.1.2 on 2024-12-28 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0028_seasons_end_at_seasons_start_at'),
        ('sales', '0022_alter_salesinquirypricelist_price_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinquiry',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bm_hunting_settings.seasons'),
        ),
    ]
