# Generated by Django 4.2.9 on 2024-10-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_rename_nationality_id_entity_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='country',
        ),
    ]
