# Generated by Django 5.1.2 on 2024-12-30 09:39

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_salesinquiry_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=sales.models.document_upload_to),
        ),
    ]
