# Generated by Django 4.2.9 on 2024-10-09 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_entity_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesiquirypreference',
            old_name='Special_requests',
            new_name='special_requests',
        ),
    ]
