# Generated by Django 5.1.2 on 2024-12-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_alter_document_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesiquirypreference',
            name='accommodation_type',
        ),
    ]
