# Generated by Django 4.2.9 on 2024-10-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_rename_special_requests_salesiquirypreference_special_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesiquirypreference',
            name='accommodation_type',
            field=models.CharField(blank=True, choices=[('Luxury', 'Luxury'), ('Budget', 'Budget'), ('Mid-Range', 'Mid-Range'), ('Cheap', 'Cheap'), ('No Preference', 'No Preference')], max_length=100, null=True),
        ),
    ]
