# Generated by Django 4.2.9 on 2024-10-09 16:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0042_remove_country_country_country_code_country_name'),
        ('sales', '0026_alter_salesiquirypreference_accommodation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('cash', 'Cash')], default='bank_transfer', max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
            },
        ),
        migrations.CreateModel(
            name='SalesInquirySpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiry_species_set', to='sales.salesinquiry')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_sales_inquiry_set', to='bm_hunting_settings.species')),
            ],
        ),
        migrations.AlterField(
            model_name='salespayment',
            name='payment_method_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_payment_method_set', to='sales.paymentmethod'),
        ),
    ]
