# Generated by Django 4.2.9 on 2024-10-09 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_salesinquiryspecies_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiry',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiry_payment_method_set', to='sales.paymentmethod'),
        ),
        migrations.AddField(
            model_name='salesinquiry',
            name='prev_experience',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
