# Generated by Django 4.2.9 on 2024-10-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_salesiquirypreference_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactTyoe',
            new_name='ContactType',
        ),
    ]
