# Generated by Django 4.2.9 on 2024-10-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_rename_contacttyoe_contacttype'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contacttype',
            table=None,
        ),
    ]
