# Generated by Django 4.2.9 on 2024-10-10 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0034_alter_contacttype_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinquiry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiry_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
