# Generated by Django 4.2.9 on 2024-10-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_alter_salesinquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='contactable',
            field=models.BooleanField(default=True),
        ),
    ]
