# Generated by Django 4.2.9 on 2024-10-10 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0045_alter_speciesunits_table'),
        ('sales', '0037_contacts_contactable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesiquirypreference',
            name='accommodation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bm_hunting_settings.accommodationtype'),
        ),
    ]
