# Generated by Django 4.2.9 on 2024-10-13 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_alter_salesiquirypreference_accommodation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiry',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
