# Generated by Django 4.2.9 on 2024-10-13 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_salesinquiry_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_type_set', to='sales.contacttype'),
        ),
    ]
