# Generated by Django 4.2.9 on 2024-10-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_alter_contacts_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacttype',
            name='name',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('address', 'Whatsapp')], max_length=100, null=True),
        ),
    ]
