# Generated by Django 4.2.9 on 2024-10-13 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_rename_preffered_date_salesiquirypreference_prefferred_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiryspecies',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='salesinquiryspecies',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
