# Generated by Django 4.2.9 on 2024-10-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_salesinquiryspecies_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinquiryspecies',
            name='sales_inquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_inquiry_species_set', to='sales.salesinquiry'),
        ),
    ]
