# Generated by Django 4.2.9 on 2024-10-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0045_alter_salesinquiryspecies_sales_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiryspecies',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
