# Generated by Django 4.2.9 on 2024-10-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0046_salesinquiryspecies_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
