# Generated by Django 4.2.9 on 2024-10-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_alter_contacts_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.CharField(max_length=100),
        ),
    ]
