# Generated by Django 4.2.9 on 2024-10-15 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0056_alter_quotahutingareaspecies_unique_together'),
        ('sales', '0048_alter_contacts_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='HuntingInquiryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('sales_inquiry', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_inquiry_area_set', to='sales.salesinquiry')),
                ('srea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_inquiry_area_set', to='bm_hunting_settings.huntingtype')),
            ],
            options={
                'verbose_name_plural': 'Hunting Inquiry Areas',
                'db_table': 'hunting_inquiry_area',
            },
        ),
    ]
