# Generated by Django 4.2.9 on 2024-10-15 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0056_alter_quotahutingareaspecies_unique_together'),
        ('sales', '0049_huntinginquiryarea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HuntingInquiryArea',
            new_name='SalesInquiryArea',
        ),
    ]
