# Generated by Django 4.2.9 on 2024-10-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0056_alter_quotahutingareaspecies_unique_together'),
        ('sales', '0053_alter_salesinquiryarea_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinquiryarea',
            name='srea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunting_inquiry_area_set', to='bm_hunting_settings.huntingarea'),
        ),
    ]
