# Generated by Django 4.2.9 on 2024-10-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_alter_salesinquiryarea_srea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesinquiryarea',
            old_name='srea',
            new_name='area',
        ),
    ]
