# Generated by Django 4.2.9 on 2024-10-18 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bm_hunting_settings', '0086_seasons'),
        ('sales', '0055_rename_srea_salesinquiryarea_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinquiry',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bm_hunting_settings.seasons'),
        ),
    ]
