# Generated by Django 4.2.9 on 2024-10-19 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0056_salesinquiry_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesiquirypreference',
            old_name='prefferred_date',
            new_name='preferred_date',
        ),
    ]
